#!/bin/bash

# Script de test automatisé pour minishell
# Généré automatiquement - 989 tests inclus
# Usage: ./test_minishell.sh [chemin_vers_minishell]

MINISHELL_PATH="./minishell"
TEST_RESULTS_FILE="test_results.txt"
TEMP_DIR="/tmp/minishell_tests_$$"
TIMEOUT_DURATION=5

# Couleurs
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Compteurs
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0
TIMEOUT_TESTS=0
SKIPPED_TESTS=0

print_status() {
    local status=$1
    local message="$2"
    case $status in
        "PASS") echo -e "${GREEN}[PASS]${NC} $message" ;;
        "FAIL") echo -e "${RED}[FAIL]${NC} $message" ;;
        "TIMEOUT") echo -e "${YELLOW}[TIMEOUT]${NC} $message" ;;
        "INFO") echo -e "${BLUE}[INFO]${NC} $message" ;;
        "SKIP") echo -e "${YELLOW}[SKIP]${NC} $message" ;;
    esac
}

cleanup() {
    rm -rf "$TEMP_DIR" 2>/dev/null
    exit ${1:-0}
}

trap cleanup EXIT SIGINT SIGTERM

check_minishell() {
    if [ ! -f "$MINISHELL_PATH" ]; then
        print_status "FAIL" "Minishell non trouvé: $MINISHELL_PATH"
        echo "Usage: $0 [chemin_vers_minishell]"
        exit 1
    fi
    
    if [ ! -x "$MINISHELL_PATH" ]; then
        print_status "FAIL" "Minishell non exécutable: $MINISHELL_PATH"
        exit 1
    fi
}

run_test() {
    local test_number=$1
    local command="$2"
    local temp_file="$TEMP_DIR/test_${test_number}"
    
    TOTAL_TESTS=$((TOTAL_TESTS + 1))
    
    mkdir -p "$TEMP_DIR"
    echo "test content" > "$TEMP_DIR/testfile.txt" 2>/dev/null
    echo -e "line1\nline2\nline3" > "$TEMP_DIR/input.txt" 2>/dev/null
    
    case "$command" in
        *"exit"* | *"quit"*)
            print_status "SKIP" "Test $test_number: $command (ignoré)"
            SKIPPED_TESTS=$((SKIPPED_TESTS + 1))
            return ;;
        "\\n (touche entrée)")
            command="" ;;
    esac
    
    if [ $((test_number % 100)) -eq 0 ]; then
        print_status "INFO" "Test $test_number/989"
    fi
    
    {
        printf "%s\n" "$command" | timeout "$TIMEOUT_DURATION" "$MINISHELL_PATH" > "$temp_file.out" 2> "$temp_file.err"
        echo $? > "$temp_file.exit"
    } &
    
    wait $! 2>/dev/null
    local wait_result=$?
    
    if [ $wait_result -eq 124 ]; then
        TIMEOUT_TESTS=$((TIMEOUT_TESTS + 1))
        echo "Test $test_number: TIMEOUT - $command" >> "$TEST_RESULTS_FILE"
    else
        local exit_code=0
        [ -f "$temp_file.exit" ] && exit_code=$(cat "$temp_file.exit" 2>/dev/null || echo "0")
        
        if [ $exit_code -ne 139 ] && [ $exit_code -ne 134 ] && [ $exit_code -ne 136 ]; then
            PASSED_TESTS=$((PASSED_TESTS + 1))
            echo "Test $test_number: PASS - $command (exit: $exit_code)" >> "$TEST_RESULTS_FILE"
        else
            FAILED_TESTS=$((FAILED_TESTS + 1))
            echo "Test $test_number: FAIL - $command (exit: $exit_code)" >> "$TEST_RESULTS_FILE"
            print_status "FAIL" "Test $test_number: $command (crash: $exit_code)"
        fi
    fi
    
    rm -f "$temp_file".* 2>/dev/null
}

main() {
    [ $# -gt 0 ] && MINISHELL_PATH="$1"
    
    check_minishell
    
    print_status "INFO" "========== TESTS MINISHELL =========="
    print_status "INFO" "Exécutable: $MINISHELL_PATH"
    print_status "INFO" "Tests: 989"
    print_status "INFO" "Résultats: $TEST_RESULTS_FILE"
    print_status "INFO" "====================================="
    
    echo "=== TESTS MINISHELL - $(date) ===" > "$TEST_RESULTS_FILE"
    echo "Exécutable: $MINISHELL_PATH" >> "$TEST_RESULTS_FILE"
    echo "Tests: 989" >> "$TEST_RESULTS_FILE"
    echo "" >> "$TEST_RESULTS_FILE"
    
    mkdir -p "$TEMP_DIR"
    cd "$TEMP_DIR" 2>/dev/null || true
    
    declare -a test_commands=(
        "\\n (touche entrée)"
        "[q"
        "[q"
        ":"
        "!"
        ">"
        "<"
        ">>"
        "<<"
        "<>"
        ">>>>>"
        ">>>>>>>>>>>>>>>"
        "<<<<<"
        "<<<<<<<<<<<<<<<<<"
        "> > > >"
        ">> >> >> >>"
        ">>>> >> >> >>"
        "/"
        "//"
        "/."
        "/./../../../../.."
        "///////"
        "-"
        "|"
        "| hola"
        "| | |"
        "||"
        "|||||"
        "|||||||||||||"
        ">>|><"
        "|><"
        "<<|>>"
        "<<<>>"
        "><<>"
        "<|>"
        "ls"
        "ls -l"
        "ls -la"
        "ls -a"
        "ls -al"
        "ls nonexistent"
        "pwd"
        "echo"
        "echo hello"
        "echo 'hello world'"
        "echo \"hello world\""
        "echo \$USER"
        "echo \$HOME"
        "echo \$PATH"
        "cat"
        "cat /etc/passwd"
        "cat nonexistent"
        "wc"
        "wc -l"
        "grep hello"
        "grep -n hello"
        "sort"
        "uniq"
        "head"
        "tail"
        "mkdir test_dir"
        "rmdir test_dir"
        "rm nonexistent"
        "cp source dest"
        "mv source dest"
        "touch newfile"
        "chmod 755 file"
        "env"
        "export VAR=value"
        "unset VAR"
        "cd"
        "cd .."
        "cd /tmp"
        "cd nonexistent"
        "history"
        "which ls"
        "whereis ls"
        "whoami"
        "date"
        "sleep 1"
        "true"
        "false"
        "test -f file"
        "[ -d directory ]"
        "./nonexistent"
        "/bin/ls"
        "/usr/bin/wc"
        "ls | wc -l"
        "echo hello | cat"
        "ls -l | grep test"
        "cat file | sort | uniq"
        "echo test > output.txt"
        "echo test >> output.txt"
        "cat < input.txt"
        "wc < /etc/passwd"
        "ls > /dev/null"
        "echo hello && echo world"
        "false && echo not_printed"
        "true || echo not_printed"
        "false || echo printed"
        "echo \$?"
        "echo \$(date)"
        "echo \`date\`"
        "echo hello; echo world"
        "echo hello ; echo world"
        "(echo hello)"
        "{ echo hello; }"
        "exit"
        "exit 0"
        "exit 1"
        "exit 42"
        "quit"
        "echo test1"
        "echo test2"
        "echo test3"
        "echo test4"
        "echo test5"
        "ls -l file5"
        "echo test6"
        "echo test7"
        "echo test8"
        "echo test9"
        "echo test10"
        "ls -l file10"
        "echo \"test 10\" | cat"
        "echo test11"
        "echo test12"
        "echo test13"
        "echo test14"
        "echo test15"
        "ls -l file15"
        "echo test16"
        "echo test17"
        "echo test18"
        "echo test19"
        "echo test20"
        "ls -l file20"
        "cat file20 | grep pattern"
        "echo \"test 20\" | cat"
        "echo test21"
        "echo test22"
        "echo test23"
        "echo test24"
        "echo test25"
        "ls -l file25"
        "echo test26"
        "echo test27"
        "echo test28"
        "echo test29"
        "echo test30"
        "ls -l file30"
        "echo \"test 30\" | cat"
        "echo test31"
        "echo test32"
        "echo test33"
        "echo test34"
        "echo test35"
        "ls -l file35"
        "echo test36"
        "echo test37"
        "echo test38"
        "echo test39"
        "echo test40"
        "ls -l file40"
        "cat file40 | grep pattern"
        "echo \"test 40\" | cat"
        "echo test41"
        "echo test42"
        "echo test43"
        "echo test44"
        "echo test45"
        "ls -l file45"
        "echo test46"
        "echo test47"
        "echo test48"
        "echo test49"
        "echo test50"
        "ls -l file50"
        "echo \"test 50\" | cat"
        "echo test51"
        "echo test52"
        "echo test53"
        "echo test54"
        "echo test55"
        "ls -l file55"
        "echo test56"
        "echo test57"
        "echo test58"
        "echo test59"
        "echo test60"
        "ls -l file60"
        "cat file60 | grep pattern"
        "echo \"test 60\" | cat"
        "echo test61"
        "echo test62"
        "echo test63"
        "echo test64"
        "echo test65"
        "ls -l file65"
        "echo test66"
        "echo test67"
        "echo test68"
        "echo test69"
        "echo test70"
        "ls -l file70"
        "echo \"test 70\" | cat"
        "echo test71"
        "echo test72"
        "echo test73"
        "echo test74"
        "echo test75"
        "ls -l file75"
        "echo test76"
        "echo test77"
        "echo test78"
        "echo test79"
        "echo test80"
        "ls -l file80"
        "cat file80 | grep pattern"
        "echo \"test 80\" | cat"
        "echo test81"
        "echo test82"
        "echo test83"
        "echo test84"
        "echo test85"
        "ls -l file85"
        "echo test86"
        "echo test87"
        "echo test88"
        "echo test89"
        "echo test90"
        "ls -l file90"
        "echo \"test 90\" | cat"
        "echo test91"
        "echo test92"
        "echo test93"
        "echo test94"
        "echo test95"
        "ls -l file95"
        "echo test96"
        "echo test97"
        "echo test98"
        "echo test99"
        "echo test100"
        "ls -l file100"
        "cat file100 | grep pattern"
        "echo \"test 100\" | cat"
        "echo test101"
        "echo test102"
        "echo test103"
        "echo test104"
        "echo test105"
        "ls -l file105"
        "echo test106"
        "echo test107"
        "echo test108"
        "echo test109"
        "echo test110"
        "ls -l file110"
        "echo \"test 110\" | cat"
        "echo test111"
        "echo test112"
        "echo test113"
        "echo test114"
        "echo test115"
        "ls -l file115"
        "echo test116"
        "echo test117"
        "echo test118"
        "echo test119"
        "echo test120"
        "ls -l file120"
        "cat file120 | grep pattern"
        "echo \"test 120\" | cat"
        "echo test121"
        "echo test122"
        "echo test123"
        "echo test124"
        "echo test125"
        "ls -l file125"
        "echo test126"
        "echo test127"
        "echo test128"
        "echo test129"
        "echo test130"
        "ls -l file130"
        "echo \"test 130\" | cat"
        "echo test131"
        "echo test132"
        "echo test133"
        "echo test134"
        "echo test135"
        "ls -l file135"
        "echo test136"
        "echo test137"
        "echo test138"
        "echo test139"
        "echo test140"
        "ls -l file140"
        "cat file140 | grep pattern"
        "echo \"test 140\" | cat"
        "echo test141"
        "echo test142"
        "echo test143"
        "echo test144"
        "echo test145"
        "ls -l file145"
        "echo test146"
        "echo test147"
        "echo test148"
        "echo test149"
        "echo test150"
        "ls -l file150"
        "echo \"test 150\" | cat"
        "echo test151"
        "echo test152"
        "echo test153"
        "echo test154"
        "echo test155"
        "ls -l file155"
        "echo test156"
        "echo test157"
        "echo test158"
        "echo test159"
        "echo test160"
        "ls -l file160"
        "cat file160 | grep pattern"
        "echo \"test 160\" | cat"
        "echo test161"
        "echo test162"
        "echo test163"
        "echo test164"
        "echo test165"
        "ls -l file165"
        "echo test166"
        "echo test167"
        "echo test168"
        "echo test169"
        "echo test170"
        "ls -l file170"
        "echo \"test 170\" | cat"
        "echo test171"
        "echo test172"
        "echo test173"
        "echo test174"
        "echo test175"
        "ls -l file175"
        "echo test176"
        "echo test177"
        "echo test178"
        "echo test179"
        "echo test180"
        "ls -l file180"
        "cat file180 | grep pattern"
        "echo \"test 180\" | cat"
        "echo test181"
        "echo test182"
        "echo test183"
        "echo test184"
        "echo test185"
        "ls -l file185"
        "echo test186"
        "echo test187"
        "echo test188"
        "echo test189"
        "echo test190"
        "ls -l file190"
        "echo \"test 190\" | cat"
        "echo test191"
        "echo test192"
        "echo test193"
        "echo test194"
        "echo test195"
        "ls -l file195"
        "echo test196"
        "echo test197"
        "echo test198"
        "echo test199"
        "echo test200"
        "ls -l file200"
        "cat file200 | grep pattern"
        "echo \"test 200\" | cat"
        "echo test201"
        "echo test202"
        "echo test203"
        "echo test204"
        "echo test205"
        "ls -l file205"
        "echo test206"
        "echo test207"
        "echo test208"
        "echo test209"
        "echo test210"
        "ls -l file210"
        "echo \"test 210\" | cat"
        "echo test211"
        "echo test212"
        "echo test213"
        "echo test214"
        "echo test215"
        "ls -l file215"
        "echo test216"
        "echo test217"
        "echo test218"
        "echo test219"
        "echo test220"
        "ls -l file220"
        "cat file220 | grep pattern"
        "echo \"test 220\" | cat"
        "echo test221"
        "echo test222"
        "echo test223"
        "echo test224"
        "echo test225"
        "ls -l file225"
        "echo test226"
        "echo test227"
        "echo test228"
        "echo test229"
        "echo test230"
        "ls -l file230"
        "echo \"test 230\" | cat"
        "echo test231"
        "echo test232"
        "echo test233"
        "echo test234"
        "echo test235"
        "ls -l file235"
        "echo test236"
        "echo test237"
        "echo test238"
        "echo test239"
        "echo test240"
        "ls -l file240"
        "cat file240 | grep pattern"
        "echo \"test 240\" | cat"
        "echo test241"
        "echo test242"
        "echo test243"
        "echo test244"
        "echo test245"
        "ls -l file245"
        "echo test246"
        "echo test247"
        "echo test248"
        "echo test249"
        "echo test250"
        "ls -l file250"
        "echo \"test 250\" | cat"
        "echo test251"
        "echo test252"
        "echo test253"
        "echo test254"
        "echo test255"
        "ls -l file255"
        "echo test256"
        "echo test257"
        "echo test258"
        "echo test259"
        "echo test260"
        "ls -l file260"
        "cat file260 | grep pattern"
        "echo \"test 260\" | cat"
        "echo test261"
        "echo test262"
        "echo test263"
        "echo test264"
        "echo test265"
        "ls -l file265"
        "echo test266"
        "echo test267"
        "echo test268"
        "echo test269"
        "echo test270"
        "ls -l file270"
        "echo \"test 270\" | cat"
        "echo test271"
        "echo test272"
        "echo test273"
        "echo test274"
        "echo test275"
        "ls -l file275"
        "echo test276"
        "echo test277"
        "echo test278"
        "echo test279"
        "echo test280"
        "ls -l file280"
        "cat file280 | grep pattern"
        "echo \"test 280\" | cat"
        "echo test281"
        "echo test282"
        "echo test283"
        "echo test284"
        "echo test285"
        "ls -l file285"
        "echo test286"
        "echo test287"
        "echo test288"
        "echo test289"
        "echo test290"
        "ls -l file290"
        "echo \"test 290\" | cat"
        "echo test291"
        "echo test292"
        "echo test293"
        "echo test294"
        "echo test295"
        "ls -l file295"
        "echo test296"
        "echo test297"
        "echo test298"
        "echo test299"
        "echo test300"
        "ls -l file300"
        "cat file300 | grep pattern"
        "echo \"test 300\" | cat"
        "echo test301"
        "echo test302"
        "echo test303"
        "echo test304"
        "echo test305"
        "ls -l file305"
        "echo test306"
        "echo test307"
        "echo test308"
        "echo test309"
        "echo test310"
        "ls -l file310"
        "echo \"test 310\" | cat"
        "echo test311"
        "echo test312"
        "echo test313"
        "echo test314"
        "echo test315"
        "ls -l file315"
        "echo test316"
        "echo test317"
        "echo test318"
        "echo test319"
        "echo test320"
        "ls -l file320"
        "cat file320 | grep pattern"
        "echo \"test 320\" | cat"
        "echo test321"
        "echo test322"
        "echo test323"
        "echo test324"
        "echo test325"
        "ls -l file325"
        "echo test326"
        "echo test327"
        "echo test328"
        "echo test329"
        "echo test330"
        "ls -l file330"
        "echo \"test 330\" | cat"
        "echo test331"
        "echo test332"
        "echo test333"
        "echo test334"
        "echo test335"
        "ls -l file335"
        "echo test336"
        "echo test337"
        "echo test338"
        "echo test339"
        "echo test340"
        "ls -l file340"
        "cat file340 | grep pattern"
        "echo \"test 340\" | cat"
        "echo test341"
        "echo test342"
        "echo test343"
        "echo test344"
        "echo test345"
        "ls -l file345"
        "echo test346"
        "echo test347"
        "echo test348"
        "echo test349"
        "echo test350"
        "ls -l file350"
        "echo \"test 350\" | cat"
        "echo test351"
        "echo test352"
        "echo test353"
        "echo test354"
        "echo test355"
        "ls -l file355"
        "echo test356"
        "echo test357"
        "echo test358"
        "echo test359"
        "echo test360"
        "ls -l file360"
        "cat file360 | grep pattern"
        "echo \"test 360\" | cat"
        "echo test361"
        "echo test362"
        "echo test363"
        "echo test364"
        "echo test365"
        "ls -l file365"
        "echo test366"
        "echo test367"
        "echo test368"
        "echo test369"
        "echo test370"
        "ls -l file370"
        "echo \"test 370\" | cat"
        "echo test371"
        "echo test372"
        "echo test373"
        "echo test374"
        "echo test375"
        "ls -l file375"
        "echo test376"
        "echo test377"
        "echo test378"
        "echo test379"
        "echo test380"
        "ls -l file380"
        "cat file380 | grep pattern"
        "echo \"test 380\" | cat"
        "echo test381"
        "echo test382"
        "echo test383"
        "echo test384"
        "echo test385"
        "ls -l file385"
        "echo test386"
        "echo test387"
        "echo test388"
        "echo test389"
        "echo test390"
        "ls -l file390"
        "echo \"test 390\" | cat"
        "echo test391"
        "echo test392"
        "echo test393"
        "echo test394"
        "echo test395"
        "ls -l file395"
        "echo test396"
        "echo test397"
        "echo test398"
        "echo test399"
        "echo test400"
        "ls -l file400"
        "cat file400 | grep pattern"
        "echo \"test 400\" | cat"
        "echo test401"
        "echo test402"
        "echo test403"
        "echo test404"
        "echo test405"
        "ls -l file405"
        "echo test406"
        "echo test407"
        "echo test408"
        "echo test409"
        "echo test410"
        "ls -l file410"
        "echo \"test 410\" | cat"
        "echo test411"
        "echo test412"
        "echo test413"
        "echo test414"
        "echo test415"
        "ls -l file415"
        "echo test416"
        "echo test417"
        "echo test418"
        "echo test419"
        "echo test420"
        "ls -l file420"
        "cat file420 | grep pattern"
        "echo \"test 420\" | cat"
        "echo test421"
        "echo test422"
        "echo test423"
        "echo test424"
        "echo test425"
        "ls -l file425"
        "echo test426"
        "echo test427"
        "echo test428"
        "echo test429"
        "echo test430"
        "ls -l file430"
        "echo \"test 430\" | cat"
        "echo test431"
        "echo test432"
        "echo test433"
        "echo test434"
        "echo test435"
        "ls -l file435"
        "echo test436"
        "echo test437"
        "echo test438"
        "echo test439"
        "echo test440"
        "ls -l file440"
        "cat file440 | grep pattern"
        "echo \"test 440\" | cat"
        "echo test441"
        "echo test442"
        "echo test443"
        "echo test444"
        "echo test445"
        "ls -l file445"
        "echo test446"
        "echo test447"
        "echo test448"
        "echo test449"
        "echo test450"
        "ls -l file450"
        "echo \"test 450\" | cat"
        "echo test451"
        "echo test452"
        "echo test453"
        "echo test454"
        "echo test455"
        "ls -l file455"
        "echo test456"
        "echo test457"
        "echo test458"
        "echo test459"
        "echo test460"
        "ls -l file460"
        "cat file460 | grep pattern"
        "echo \"test 460\" | cat"
        "echo test461"
        "echo test462"
        "echo test463"
        "echo test464"
        "echo test465"
        "ls -l file465"
        "echo test466"
        "echo test467"
        "echo test468"
        "echo test469"
        "echo test470"
        "ls -l file470"
        "echo \"test 470\" | cat"
        "echo test471"
        "echo test472"
        "echo test473"
        "echo test474"
        "echo test475"
        "ls -l file475"
        "echo test476"
        "echo test477"
        "echo test478"
        "echo test479"
        "echo test480"
        "ls -l file480"
        "cat file480 | grep pattern"
        "echo \"test 480\" | cat"
        "echo test481"
        "echo test482"
        "echo test483"
        "echo test484"
        "echo test485"
        "ls -l file485"
        "echo test486"
        "echo test487"
        "echo test488"
        "echo test489"
        "echo test490"
        "ls -l file490"
        "echo \"test 490\" | cat"
        "echo test491"
        "echo test492"
        "echo test493"
        "echo test494"
        "echo test495"
        "ls -l file495"
        "echo test496"
        "echo test497"
        "echo test498"
        "echo test499"
        "echo test500"
        "ls -l file500"
        "cat file500 | grep pattern"
        "echo \"test 500\" | cat"
        "echo test501"
        "echo test502"
        "echo test503"
        "echo test504"
        "echo test505"
        "ls -l file505"
        "echo test506"
        "echo test507"
        "echo test508"
        "echo test509"
        "echo test510"
        "ls -l file510"
        "echo \"test 510\" | cat"
        "echo test511"
        "echo test512"
        "echo test513"
        "echo test514"
        "echo test515"
        "ls -l file515"
        "echo test516"
        "echo test517"
        "echo test518"
        "echo test519"
        "echo test520"
        "ls -l file520"
        "cat file520 | grep pattern"
        "echo \"test 520\" | cat"
        "echo test521"
        "echo test522"
        "echo test523"
        "echo test524"
        "echo test525"
        "ls -l file525"
        "echo test526"
        "echo test527"
        "echo test528"
        "echo test529"
        "echo test530"
        "ls -l file530"
        "echo \"test 530\" | cat"
        "echo test531"
        "echo test532"
        "echo test533"
        "echo test534"
        "echo test535"
        "ls -l file535"
        "echo test536"
        "echo test537"
        "echo test538"
        "echo test539"
        "echo test540"
        "ls -l file540"
        "cat file540 | grep pattern"
        "echo \"test 540\" | cat"
        "echo test541"
        "echo test542"
        "echo test543"
        "echo test544"
        "echo test545"
        "ls -l file545"
        "echo test546"
        "echo test547"
        "echo test548"
        "echo test549"
        "echo test550"
        "ls -l file550"
        "echo \"test 550\" | cat"
        "echo test551"
        "echo test552"
        "echo test553"
        "echo test554"
        "echo test555"
        "ls -l file555"
        "echo test556"
        "echo test557"
        "echo test558"
        "echo test559"
        "echo test560"
        "ls -l file560"
        "cat file560 | grep pattern"
        "echo \"test 560\" | cat"
        "echo test561"
        "echo test562"
        "echo test563"
        "echo test564"
        "echo test565"
        "ls -l file565"
        "echo test566"
        "echo test567"
        "echo test568"
        "echo test569"
        "echo test570"
        "ls -l file570"
        "echo \"test 570\" | cat"
        "echo test571"
        "echo test572"
        "echo test573"
        "echo test574"
        "echo test575"
        "ls -l file575"
        "echo test576"
        "echo test577"
        "echo test578"
        "echo test579"
        "echo test580"
        "ls -l file580"
        "cat file580 | grep pattern"
        "echo \"test 580\" | cat"
        "echo test581"
        "echo test582"
        "echo test583"
        "echo test584"
        "echo test585"
        "ls -l file585"
        "echo test586"
        "echo test587"
        "echo test588"
        "echo test589"
        "echo test590"
        "ls -l file590"
        "echo \"test 590\" | cat"
        "echo test591"
        "echo test592"
        "echo test593"
        "echo test594"
        "echo test595"
        "ls -l file595"
        "echo test596"
        "echo test597"
        "echo test598"
        "echo test599"
        "echo test600"
        "ls -l file600"
        "cat file600 | grep pattern"
        "echo \"test 600\" | cat"
        "echo test601"
        "echo test602"
        "echo test603"
        "echo test604"
        "echo test605"
        "ls -l file605"
        "echo test606"
        "echo test607"
        "echo test608"
        "echo test609"
        "echo test610"
        "ls -l file610"
        "echo \"test 610\" | cat"
        "echo test611"
        "echo test612"
        "echo test613"
        "echo test614"
        "echo test615"
        "ls -l file615"
        "echo test616"
        "echo test617"
        "echo test618"
        "echo test619"
        "echo test620"
        "ls -l file620"
        "cat file620 | grep pattern"
        "echo \"test 620\" | cat"
        "echo test621"
        "echo test622"
        "echo test623"
        "echo test624"
        "echo test625"
        "ls -l file625"
        "echo test626"
        "echo test627"
        "echo test628"
        "echo test629"
        "echo test630"
        "ls -l file630"
        "echo \"test 630\" | cat"
        "echo test631"
        "echo test632"
        "echo test633"
        "echo test634"
        "echo test635"
        "ls -l file635"
        "echo test636"
        "echo test637"
        "echo test638"
        "echo test639"
        "echo test640"
        "ls -l file640"
        "cat file640 | grep pattern"
        "echo \"test 640\" | cat"
        "echo test641"
        "echo test642"
        "echo test643"
        "echo test644"
        "echo test645"
        "ls -l file645"
        "echo test646"
        "echo test647"
        "echo test648"
        "echo test649"
        "echo test650"
        "ls -l file650"
        "echo \"test 650\" | cat"
    )
    
    print_status "INFO" "Début des tests..."
    local test_number=1
    for command in "${test_commands[@]}"; do
        run_test $test_number "$command"
        test_number=$((test_number + 1))
        sleep 0.01
    done
    
    echo ""
    print_status "INFO" "=========== RÉSUMÉ ==========="
    print_status "INFO" "Total: $TOTAL_TESTS"
    print_status "INFO" "Réussis: $PASSED_TESTS"
    print_status "INFO" "Échoués: $FAILED_TESTS"
    print_status "INFO" "Timeouts: $TIMEOUT_TESTS"
    print_status "INFO" "Ignorés: $SKIPPED_TESTS"
    
    local effective_tests=$((TOTAL_TESTS - SKIPPED_TESTS))
    local success_rate=0
    [ $effective_tests -gt 0 ] && success_rate=$((PASSED_TESTS * 100 / effective_tests))
    
    print_status "INFO" "Taux réussite: ${success_rate}%"
    print_status "INFO" "=============================="
    
    cat >> "$TEST_RESULTS_FILE" << EOF

=== RÉSUMÉ ===
Total: $TOTAL_TESTS
Réussis: $PASSED_TESTS
Échoués: $FAILED_TESTS
Timeouts: $TIMEOUT_TESTS
Ignorés: $SKIPPED_TESTS
Taux: ${success_rate}%
Fin: $(date)
EOF
    
    print_status "INFO" "Résultats dans: $TEST_RESULTS_FILE"
    
    if [ $FAILED_TESTS -gt 0 ]; then
        print_status "INFO" "Analyse: grep 'FAIL' $TEST_RESULTS_FILE"
    fi
    
    [ $FAILED_TESTS -gt 0 ] && exit 1 || exit 0
}

main "$@"
